name: screen_down_detector
description: A Flutter widget that detects when a device is placed with its screen facing down.
version: 0.0.1
repository: https://github.com/starig/screen_down_detector
issue_tracker: https://github.com/starig/screen_down_detector/issues

topics:
  - accelerometer
  - device-orientation
  - sensors

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^7.1.0

dev_dependencies:
  fake_async: ^1.3.3
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
